ALTER TABLE poems ADD COLUMN IF NOT EXISTS pinyin TEXT;
ALTER TABLE poems ADD COLUMN IF NOT EXISTS translation TEXT;
ALTER TABLE poems ADD COLUMN IF NOT EXISTS story TEXT;
ALTER TABLE poems ADD COLUMN IF NOT EXISTS parent_guide TEXT;
ALTER TABLE poems ADD COLUMN IF NOT EXISTS difficulty INTEGER NOT NULL DEFAULT 1;
ALTER TABLE poems ADD COLUMN IF NOT EXISTS season TEXT NOT NULL DEFAULT 'any';
ALTER TABLE poems ADD COLUMN IF NOT EXISTS video_available BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE poems ADD COLUMN IF NOT EXISTS card_unlocked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE poems ADD COLUMN IF NOT EXISTS annotated_content_json TEXT NOT NULL DEFAULT '[]';
