CREATE TABLE IF NOT EXISTS poem_line_timings (
    poem_id INTEGER PRIMARY KEY REFERENCES poems(id) ON DELETE CASCADE,
    lines_json JSONB NOT NULL,
    source TEXT NOT NULL DEFAULT 'funasr',
    status TEXT NOT NULL,
    match_ratio NUMERIC(5,3),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO poem_line_timings (poem_id, lines_json, source, status, match_ratio, updated_at) VALUES (49, '[{"index": 0, "text": "半亩方塘一鉴开，", "start": 2.73, "end": 4.69, "segments": 7, "source": "funasr_align"}, {"index": 1, "text": "天光云影共徘徊。", "start": 4.95, "end": 6.95, "segments": 7, "source": "funasr_align"}, {"index": 2, "text": "问渠那得清如许，", "start": 7.17, "end": 9.03, "segments": 7, "source": "funasr_align"}, {"index": 3, "text": "为有源头活水来。", "start": 9.19, "end": 11.125, "segments": 7, "source": "funasr_align"}]'::jsonb, 'funasr_mac', 'funasr_aligned_v3', 1.0, NOW()) ON CONFLICT (poem_id) DO UPDATE SET lines_json=EXCLUDED.lines_json, source=EXCLUDED.source, status=EXCLUDED.status, match_ratio=EXCLUDED.match_ratio, updated_at=NOW();
INSERT INTO poem_line_timings (poem_id, lines_json, source, status, match_ratio, updated_at) VALUES (52, '[{"index": 0, "text": "春种一粒粟，", "start": 2.71, "end": 4.09, "segments": 5, "source": "funasr_align"}, {"index": 1, "text": "秋收万颗子。", "start": 4.33, "end": 5.75, "segments": 5, "source": "funasr_align"}, {"index": 2, "text": "四海无闲田，", "start": 5.85, "end": 7.29, "segments": 5, "source": "funasr_align"}, {"index": 3, "text": "农夫犹饿死。", "start": 7.63, "end": 8.965, "segments": 5, "source": "funasr_align"}]'::jsonb, 'funasr_mac', 'funasr_aligned_v3', 1.0, NOW()) ON CONFLICT (poem_id) DO UPDATE SET lines_json=EXCLUDED.lines_json, source=EXCLUDED.source, status=EXCLUDED.status, match_ratio=EXCLUDED.match_ratio, updated_at=NOW();
INSERT INTO poem_line_timings (poem_id, lines_json, source, status, match_ratio, updated_at) VALUES (113, '[{"index": 0, "text": "多情却似总无情，", "start": 2.19, "end": 4.15, "segments": 7, "source": "funasr_align"}, {"index": 1, "text": "唯觉樽前笑不成。", "start": 4.41, "end": 6.47, "segments": 7, "source": "funasr_align"}, {"index": 2, "text": "蜡烛有心还惜别，", "start": 6.65, "end": 8.55, "segments": 7, "source": "funasr_align"}, {"index": 3, "text": "替人垂泪到天明。", "start": 8.73, "end": 10.675, "segments": 7, "source": "funasr_align"}]'::jsonb, 'funasr_mac', 'funasr_aligned_v3', 1.0, NOW()) ON CONFLICT (poem_id) DO UPDATE SET lines_json=EXCLUDED.lines_json, source=EXCLUDED.source, status=EXCLUDED.status, match_ratio=EXCLUDED.match_ratio, updated_at=NOW();
INSERT INTO poem_line_timings (poem_id, lines_json, source, status, match_ratio, updated_at) VALUES (116, '[{"index": 0, "text": "相见时难别亦难，", "start": 2.57, "end": 4.51, "segments": 7, "source": "funasr_align"}, {"index": 1, "text": "东风无力百花残。", "start": 4.67, "end": 6.59, "segments": 7, "source": "funasr_align"}, {"index": 2, "text": "春蚕到死丝方尽，", "start": 6.83, "end": 8.85, "segments": 7, "source": "funasr_align"}, {"index": 3, "text": "蜡炬成灰泪始干。", "start": 9.05, "end": 11.065, "segments": 7, "source": "funasr_align"}]'::jsonb, 'funasr_mac', 'funasr_aligned_v3', 1.0, NOW()) ON CONFLICT (poem_id) DO UPDATE SET lines_json=EXCLUDED.lines_json, source=EXCLUDED.source, status=EXCLUDED.status, match_ratio=EXCLUDED.match_ratio, updated_at=NOW();
INSERT INTO poem_line_timings (poem_id, lines_json, source, status, match_ratio, updated_at) VALUES (124, '[{"index": 0, "text": "山中相送罢，", "start": 2.39, "end": 3.91, "segments": 5, "source": "funasr_align"}, {"index": 1, "text": "日暮掩柴扉。", "start": 4.05, "end": 5.45, "segments": 5, "source": "funasr_align"}, {"index": 2, "text": "春草明年绿，", "start": 5.59, "end": 7.11, "segments": 5, "source": "funasr_align"}, {"index": 3, "text": "王孙归不归。", "start": 7.17, "end": 8.605, "segments": 5, "source": "funasr_align"}]'::jsonb, 'funasr_mac', 'funasr_aligned_v3', 1.0, NOW()) ON CONFLICT (poem_id) DO UPDATE SET lines_json=EXCLUDED.lines_json, source=EXCLUDED.source, status=EXCLUDED.status, match_ratio=EXCLUDED.match_ratio, updated_at=NOW();
INSERT INTO poem_line_timings (poem_id, lines_json, source, status, match_ratio, updated_at) VALUES (129, '[{"index": 0, "text": "荆溪白石出，", "start": 0.03, "end": 3.91, "segments": 5, "source": "funasr_align"}, {"index": 1, "text": "天寒红叶稀。", "start": 4.13, "end": 5.63, "segments": 5, "source": "funasr_align"}, {"index": 2, "text": "山路元无雨，", "start": 5.79, "end": 7.23, "segments": 5, "source": "funasr_align"}, {"index": 3, "text": "空翠湿人衣。", "start": 7.39, "end": 8.755, "segments": 5, "source": "funasr_align"}]'::jsonb, 'funasr_mac', 'funasr_aligned_v3', 1.0, NOW()) ON CONFLICT (poem_id) DO UPDATE SET lines_json=EXCLUDED.lines_json, source=EXCLUDED.source, status=EXCLUDED.status, match_ratio=EXCLUDED.match_ratio, updated_at=NOW();
INSERT INTO poem_line_timings (poem_id, lines_json, source, status, match_ratio, updated_at) VALUES (163, '[{"index": 0, "text": "黄四娘家花满蹊，", "start": 3.89, "end": 5.89, "segments": 7, "source": "funasr_align"}, {"index": 1, "text": "千朵万朵压枝低。", "start": 6.17, "end": 7.97, "segments": 7, "source": "funasr_align"}, {"index": 2, "text": "留连戏蝶时时舞，", "start": 8.05, "end": 9.99, "segments": 7, "source": "funasr_align"}, {"index": 3, "text": "自在娇莺恰恰啼。", "start": 10.19, "end": 12.295, "segments": 7, "source": "funasr_align"}]'::jsonb, 'funasr_mac', 'funasr_aligned_v3', 1.0, NOW()) ON CONFLICT (poem_id) DO UPDATE SET lines_json=EXCLUDED.lines_json, source=EXCLUDED.source, status=EXCLUDED.status, match_ratio=EXCLUDED.match_ratio, updated_at=NOW();

